"""Tests for the --wrap-existing v1→v2 region-marker migration helper."""

from __future__ import annotations

import ast

import pytest

from django_aqueduct.codegen.regions import generated_regions, merge
from django_aqueduct.codegen.wrap_existing import WrapExistingError, wrap_existing

# Shape produced by the removed v1 generator, then hand-refined by an
# integration PR: flat fields, no markers, a hand-written validator appended.
V1_STYLE_SOURCE = '''# ruff: noqa
# This file was generated by django-aqueduct.
# Run `manage.py generate_aqueduct_settings` to regenerate.

from __future__ import annotations

import datetime

from typing import Any

from pydantic import Field, model_validator
from pydantic_settings import BaseSettings, SettingsConfigDict


class AqueductSettings(BaseSettings):
    """Typed Django settings model."""

    model_config = SettingsConfigDict(
        env_prefix="",
        extra="allow",
    )

    DEBUG: bool = Field(default=False)
    DATABASE_URL: str = Field(default="sqlite:///db.sqlite3")
    SESSION_AGE: datetime.timedelta = Field(
        default_factory=lambda: datetime.timedelta(days=14)
    )
    DATABASES: dict[str, Any] = Field(default_factory=dict)

    @model_validator(mode="after")
    def build_databases(self) -> "AqueductSettings":
        import dj_database_url

        self.DATABASES = {"default": dj_database_url.parse(self.DATABASE_URL)}
        return self
'''


def test_wrap_preserves_bytes_except_markers():
    wrapped = wrap_existing(V1_STYLE_SOURCE)
    stripped = "\n".join(
        line
        for line in wrapped.splitlines()
        if "# >>> aqueduct:" not in line and "# <<< aqueduct:" not in line
    )
    assert stripped == V1_STYLE_SOURCE.rstrip("\n")


def test_wrap_inserts_all_three_regions():
    wrapped = wrap_existing(V1_STYLE_SOURCE)
    for marker in (
        "# >>> aqueduct:generated:imports",
        "# <<< aqueduct:generated:imports",
        "    # >>> aqueduct:generated:fields",
        "    # <<< aqueduct:generated:fields",
        "    # >>> aqueduct:preserved:validators",
        "    # <<< aqueduct:preserved:validators",
    ):
        assert marker in wrapped, marker


def test_wrap_keeps_hand_written_validator_in_preserved_region():
    wrapped = wrap_existing(V1_STYLE_SOURCE)
    assert "def build_databases(self)" in wrapped
    validators_start = wrapped.index("# >>> aqueduct:preserved:validators")
    assert wrapped.index("def build_databases") > validators_start


def test_wrap_fields_region_contains_only_field_declarations():
    wrapped = wrap_existing(V1_STYLE_SOURCE)
    regions = generated_regions(wrapped)
    assert "DEBUG: bool" in regions["fields"]
    assert "DATABASES: dict[str, Any]" in regions["fields"]
    assert "def build_databases" not in regions["fields"]


def test_wrap_output_is_valid_python():
    wrapped = wrap_existing(V1_STYLE_SOURCE)
    ast.parse(wrapped)


def test_wrapped_file_accepts_a_merge():
    """The wrapped output is a valid merge target for a fresh render sharing its IDs."""
    wrapped = wrap_existing(V1_STYLE_SOURCE)
    fresh = generated_regions(wrapped)
    # Simulate a regeneration that only changes the fields region body.
    new_generated = wrapped.replace(
        "DEBUG: bool = Field(default=False)",
        "DEBUG: bool = Field(default=True)",
    )
    merged = merge(wrapped, new_generated)
    assert "DEBUG: bool = Field(default=True)" in merged
    assert "def build_databases(self)" in merged
    assert fresh  # sanity: regions were actually found


def test_already_wrapped_source_rejected():
    wrapped = wrap_existing(V1_STYLE_SOURCE)
    with pytest.raises(WrapExistingError, match="already contains"):
        wrap_existing(wrapped)


def test_no_basesettings_class_rejected():
    with pytest.raises(WrapExistingError, match="No class deriving from BaseSettings"):
        wrap_existing("X = 1\n")


def test_ambiguous_classes_require_class_name():
    src = (
        "from pydantic_settings import BaseSettings\n\n"
        "class A(BaseSettings):\n    X: int = 1\n\n"
        "class B(BaseSettings):\n    Y: int = 2\n"
    )
    with pytest.raises(WrapExistingError, match="Multiple BaseSettings"):
        wrap_existing(src)
    wrapped = wrap_existing(src, class_name="B")
    assert "Y: int" in generated_regions(wrapped)["fields"]


def test_no_field_declarations_rejected():
    src = (
        "from pydantic_settings import BaseSettings\n\n"
        "class AqueductSettings(BaseSettings):\n"
        "    def foo(self):\n"
        "        return 1\n"
    )
    with pytest.raises(WrapExistingError, match="No typed field declarations"):
        wrap_existing(src)


def test_class_without_validators_after_fields():
    src = (
        "from pydantic_settings import BaseSettings\n\n"
        "class AqueductSettings(BaseSettings):\n"
        "    X: int = 1\n"
    )
    wrapped = wrap_existing(src)
    assert "aqueduct:preserved:validators" not in wrapped
    assert "X: int" in generated_regions(wrapped)["fields"]


def test_no_imports_is_tolerated():
    # No top-level import statements at all (imports_span is None) — the
    # class/field detection doesn't require BaseSettings to actually resolve.
    src = "class AqueductSettings(BaseSettings):\n    X: int = 1\n"
    wrapped = wrap_existing(src)
    assert "aqueduct:generated:imports" not in wrapped
    assert "X: int" in generated_regions(wrapped)["fields"]
