"""Pydantic BaseSettings model generator from discovered fields."""

from collections import defaultdict
from typing import Any

from django_aqueduct.discovery.base import DiscoveredField

_HEADER = """\
# This file was generated by django-aqueduct.
# Run `manage.py generate_aqueduct_settings` to regenerate.
#
# Review all fields marked with "# TODO: refine type" and update the
# annotation to a more precise type where possible.
#
# Add model validators below the last field group to derive complex
# settings objects from simpler primitives.

from __future__ import annotations

from typing import Any

from pydantic_settings import BaseSettings, SettingsConfigDict


"""

_CLASS_OPEN = """\
class AqueductSettings(BaseSettings):
    \"\"\"Typed Django settings model.

    Populate from environment variables, YAML, Vault, AWS SSM, or any
    combination by configuring ``model_config`` and the sources below.
    \"\"\"

    model_config = SettingsConfigDict(
        env_prefix="",
        extra="allow",
    )

"""

_VALIDATOR_STUB = """\
    # TODO: add model_validators here
    # Example:
    #   @model_validator(mode="after")
    #   def build_databases(self) -> "AqueductSettings":
    #       import dj_database_url
    #       self.DATABASES = {"default": dj_database_url.parse(self.DATABASE_URL)}
    #       return self
"""


def _repr_default(value: Any) -> tuple[str, bool]:
    """Produce a safe repr string for use as a Pydantic Field default.

    Returns a tuple of ``(repr_string, is_factory)`` where ``is_factory``
    indicates that the caller should use ``default_factory=lambda: ...``
    instead of ``default=...``.

    Args:
        value: The default value.

    Returns:
        A 2-tuple of (repr string, is_factory flag).
    """
    if value is None:
        return ("None", False)
    if isinstance(value, bool):
        return (repr(value), False)
    if isinstance(value, int | float):
        return (repr(value), False)
    if isinstance(value, str):
        return (repr(value), False)
    if isinstance(value, list | dict):
        # Use default_factory for mutable defaults
        return (repr(value), True)
    return (repr(value), False)


def _render_field(field: DiscoveredField) -> str:
    """Render a single field line with annotation, default, and Field() call.

    Args:
        field: The discovered field to render.

    Returns:
        A single-line string like
        ``    MY_SETTING: str = Field(default="x", description="desc")``
    """  # noqa: E501
    annotation = field.type_annotation
    default_repr, is_factory = _repr_default(field.default)
    description = field.description.replace('"', '\\"')

    if is_factory:
        default_part = f"default_factory=lambda: {default_repr}"
    else:
        default_part = f"default={default_repr}"

    parts = [default_part]
    if description:
        parts.append(f'description="{description}"')

    field_call = f"Field({', '.join(parts)})"
    suffix = "  # TODO: refine type" if field.needs_refinement else ""
    dev_comment = "  # dev-only" if field.dev_only else ""

    return f"    {field.name}: {annotation} = {field_call}{suffix}{dev_comment}"


class SettingsModelGenerator:
    """Generate a Pydantic ``BaseSettings`` module from discovered fields.

    Args:
        fields: The complete list of :class:`~django_aqueduct.discovery.base.DiscoveredField`
            objects to render, typically merged from multiple inspectors.

    Example::

        from django_aqueduct.codegen.generator import SettingsModelGenerator
        from django_aqueduct.discovery.module import ModuleInspector

        fields = ModuleInspector("myapp.settings").discover()
        print(SettingsModelGenerator(fields).render())
    """  # noqa: E501

    def __init__(self, fields: list[DiscoveredField]) -> None:
        """Store the fields to render."""
        self._fields = fields

    def render(self) -> str:
        """Render the complete ``settings_model.py`` file as a string.

        Fields are grouped by ``source_module`` under section comments.
        Within each group fields appear in the order they were supplied
        (callers should sort before passing if determinism matters).

        Returns:
            A complete, ``ast.parse``-able Python source string.
        """
        groups: dict[str, list[DiscoveredField]] = defaultdict(list)
        for f in self._fields:
            groups[f.source_module].append(f)

        lines: list[str] = [_HEADER, _CLASS_OPEN]

        for module_name, module_fields in groups.items():
            lines.append(f"    # ===== {module_name} =====\n")
            for field in module_fields:
                lines.append(_render_field(field) + "\n")
            lines.append("\n")

        lines.append(_VALIDATOR_STUB)
        lines.append("\n")

        return "".join(lines)
