"""Pydantic BaseSettings model generator from discovered fields."""

from __future__ import annotations

import os
from collections import defaultdict
from typing import TYPE_CHECKING, Any

from django_aqueduct.discovery.base import DiscoveredField, ValueKind

if TYPE_CHECKING:
    from django_aqueduct.codegen.dict_schema import TypedDictDef  # pragma: no cover

# ---------------------------------------------------------------------------
# Static header fragments
# ---------------------------------------------------------------------------

_COMMENT_BLOCK = """\
# This file was generated by django-aqueduct.
# Run `manage.py generate_aqueduct_settings` to regenerate.
#
# Review all fields marked with "# TODO: refine type" and update the
# annotation to a more precise type where possible.
#
# Add model validators below the last field group to derive complex
# settings objects from simpler primitives.
"""

_CLASS_OPEN = """\

class AqueductSettings(BaseSettings):
    \"\"\"Typed Django settings model.

    Populate from environment variables, YAML, Vault, AWS SSM, or any
    combination by configuring ``model_config`` and the sources below.
    \"\"\"

    model_config = SettingsConfigDict(
        env_prefix="",
        extra="allow",
    )

"""

_VALIDATOR_STUB = """\
    # TODO: add model_validators here
    # Example:
    #   @model_validator(mode="after")
    #   def build_databases(self) -> "AqueductSettings":
    #       import dj_database_url
    #       self.DATABASES = {"default": dj_database_url.parse(self.DATABASE_URL)}
    #       return self
"""


def _build_header(*, include_typeddict: bool) -> str:
    """Build the import block for the generated file.

    Args:
        include_typeddict: When ``True``, ``TypedDict`` is added to the
            ``from typing import …`` line.

    Returns:
        A string containing the comment block, ``from __future__`` import,
        and all necessary ``import`` statements.
    """
    typing_names = ["Any"]
    if include_typeddict:
        typing_names.append("TypedDict")
    typing_line = f"from typing import {', '.join(sorted(typing_names))}"

    return (
        f"{_COMMENT_BLOCK}\n"
        f"from __future__ import annotations\n\n"
        f"import datetime\n"
        f"import pathlib\n\n"
        f"{typing_line}\n\n"
        f"from pydantic import Field\n"
        f"from pydantic_settings import BaseSettings, SettingsConfigDict\n"
    )


# ---------------------------------------------------------------------------
# Default-value rendering
# ---------------------------------------------------------------------------


def _safe_repr(value: Any) -> str | None:
    """Return ``repr(value)`` or ``None`` if ``repr`` raises or produces bad output.

    Calling ``repr()`` on Django lazy-translation strings or other proxy
    objects may raise ``ImproperlyConfigured`` when Django has not been
    set up.  This helper swallows such exceptions and returns ``None``
    instead, so callers can fall back to a ``default=None`` declaration.

    Args:
        value: Any Python object.

    Returns:
        The repr string, or ``None`` if repr raised.
    """
    try:
        return repr(value)
    except Exception:  # noqa: BLE001
        return None


def _repr_default(value: Any) -> tuple[str, bool]:
    """Produce a repr string and ``is_factory`` flag for a Pydantic Field default.

    ``is_factory=True`` means the caller should use
    ``default_factory=lambda: <repr>`` instead of ``default=<repr>``
    (required for mutable defaults such as ``list``, ``dict``, ``set``).

    Immutable containers (``tuple``) use ``default=`` directly because
    Pydantic accepts them without a factory, and the repr may still
    contain angle brackets (class references) which the caller must
    check separately.

    ``pathlib.Path`` instances are converted to plain strings so that
    the generated file does not need a ``pathlib`` import.

    Args:
        value: The default value to represent.

    Returns:
        A 2-tuple of ``(repr_string, is_factory)``.
    """
    if value is None:
        return ("None", False)
    if isinstance(value, bool):
        return (repr(value), False)
    if isinstance(value, int | float):
        return (repr(value), False)
    if isinstance(value, str):
        return (repr(value), False)
    if isinstance(value, os.PathLike):
        # Preserve as pathlib.Path so callers can use the / operator.
        # os.fspath() extracts the str representation for any PathLike.
        return (f"pathlib.Path({repr(os.fspath(value))})", False)
    if isinstance(value, list | dict):
        r = _safe_repr(value)
        if r is None:
            return ("None", False)  # repr failed (e.g. lazy-string element)
        return (r, True)  # mutable → factory
    if isinstance(value, tuple):
        r = _safe_repr(value)
        if r is None:
            return ("None", False)
        return (r, False)  # immutable → direct default; caller checks repr
    if isinstance(value, set | frozenset):
        r = _safe_repr(value)
        if r is None:
            return ("None", False)
        return (r, True)  # mutable → factory
    r = _safe_repr(value)
    if r is None:
        return ("None", False)
    return (r, False)


def _nullable_annotation(annotation: str) -> str:
    """Widen *annotation* so that ``None`` is an accepted value.

    Any field rendered with ``default=None`` (DERIVED, CALLABLE, or an
    OPAQUE value whose ``repr`` could not be serialised) must accept
    ``None`` at runtime — otherwise a source that supplies ``None`` (or an
    absent value resolving to ``None``) raises a Pydantic ``ValidationError``
    at instantiation, before the adapter ever runs.  This was the cause of
    the ``JWT_AUTH`` / ``CELERYBEAT_SCHEDULE`` boot crashes: their dict
    defaults contained non-serialisable elements, so the generator fell back
    to ``default=None`` while keeping the non-nullable ``dict[str, Any]``
    annotation.

    ``Any`` already accepts ``None`` and an annotation that is already
    optional is returned unchanged.

    Args:
        annotation: The rendered type annotation string.

    Returns:
        The annotation, widened with ``| None`` when necessary.
    """
    a = annotation.strip()
    if a in ("Any", "None"):
        return a
    if "None" in a or a.startswith("Optional["):
        return a
    return f"{a} | None"


def _render_typeddict(td: TypedDictDef) -> str:
    """Render a ``TypedDict`` class definition as a source code string.

    All generated TypedDicts use ``total=False`` so that partial configs
    (e.g. a database entry that omits optional keys) remain valid.

    Args:
        td: The :class:`~django_aqueduct.codegen.dict_schema.TypedDictDef`
            to render.

    Returns:
        A complete class definition string including a trailing newline.
    """
    lines = [f"class {td.class_name}(TypedDict, total=False):"]
    if not td.fields:
        lines.append("    pass")
    else:
        for f in td.fields:
            lines.append(f"    {f.name}: {f.annotation}")
    lines.append("")
    return "\n".join(lines) + "\n"


def _render_field(
    f: DiscoveredField,
    annotation_override: str | None = None,
) -> str:
    """Render a single settings field as a Pydantic ``Field`` declaration.

    The rendered line has the form::

        FIELD_NAME: annotation = Field(default=...[, description="..."])  # comment

    The ``ValueKind`` of the field controls how the default is rendered:

    * ``STATIC`` — uses a Python literal or ``default_factory=lambda:``.
    * ``OPAQUE`` — attempts ``repr()``; falls back to ``None`` when the
      repr contains angle brackets (e.g. a tuple of class references).
    * ``CALLABLE`` — emits ``default=None`` with an explanatory comment.
    * ``DERIVED`` — emits ``default=None`` with a ``@model_validator``
      reminder.

    Args:
        f: The :class:`~django_aqueduct.discovery.base.DiscoveredField`
            to render.
        annotation_override: When provided, overrides
            ``f.type_annotation`` (used for genson-enriched dict types).

    Returns:
        A single-line string (no trailing newline).
    """
    annotation = annotation_override or f.type_annotation
    description = f.description.replace('"', '\\"')
    suffix = ""

    # ------------------------------------------------------------------ #
    # Determine default expression                                        #
    # ------------------------------------------------------------------ #
    if f.value_kind == ValueKind.DERIVED:
        default_expr = "default=None"
        suffix = (
            "  # DERIVED: computed from other settings"
            " — add a @model_validator to reproduce"
        )

    elif f.value_kind == ValueKind.CALLABLE:
        callable_name = getattr(f.default, "__name__", type(f.default).__name__)
        default_expr = "default=None"
        suffix = f"  # CALLABLE DEFAULT: {callable_name!r}"

    elif f.value_kind == ValueKind.REDACTED:
        default_expr = "default=None"
        suffix = (
            "  # REDACTED: name looks secret-like; the live value observed"
            " during generation was NOT written here — set explicitly"
        )

    else:
        # STATIC or OPAQUE
        default_repr, is_factory = _repr_default(f.default)

        if "<" in default_repr:
            # The repr contains non-serialisable elements (class references,
            # object pointers, etc.) — fall back to None.
            type_name = type(f.default).__name__
            default_expr = "default=None"
            suffix = f"  # OPAQUE: original {type_name} value is not serialisable"
        else:
            if is_factory:
                default_expr = f"default_factory=lambda: {default_repr}"
            else:
                default_expr = f"default={default_repr}"
            if f.needs_refinement:
                suffix = "  # TODO: refine type"

    # A ``default=None`` is only valid if the annotation accepts ``None``.
    # Widen it so a source supplying ``None`` (or an absent value) validates
    # cleanly instead of crashing at instantiation.
    if default_expr == "default=None":
        annotation = _nullable_annotation(annotation)

    # ------------------------------------------------------------------ #
    # Assemble Field() call                                               #
    # ------------------------------------------------------------------ #
    parts = [default_expr]
    if description:
        parts.append(f'description="{description}"')

    field_call = f"Field({', '.join(parts)})"
    dev_comment = "  # dev-only" if f.dev_only else ""

    return f"    {f.name}: {annotation} = {field_call}{suffix}{dev_comment}"


# ---------------------------------------------------------------------------
# Main generator
# ---------------------------------------------------------------------------


class SettingsModelGenerator:
    """Generate a Pydantic ``BaseSettings`` module from discovered fields.

    When ``genson`` is installed (via the ``[codegen]`` extra), dict-valued
    settings receive enriched type annotations and companion ``TypedDict``
    class definitions are emitted before the main settings class.

    Args:
        fields: The complete list of
            :class:`~django_aqueduct.discovery.base.DiscoveredField`
            objects to render, typically merged from multiple inspectors.

    Example::

        from django_aqueduct.codegen.generator import SettingsModelGenerator
        from django_aqueduct.discovery.module import ModuleInspector

        fields = ModuleInspector("myapp.settings").discover()
        print(SettingsModelGenerator(fields).render())
    """

    def __init__(self, fields: list[DiscoveredField]) -> None:
        """Store the fields to render."""
        self._fields = fields

    def render(self) -> str:
        """Render the complete ``settings_model.py`` file as a string.

        When ``owning_package`` is populated on any field (via
        :class:`~django_aqueduct.discovery.package_attributor.PackageAttributor`)
        fields are grouped by package instead of source module.  The group
        order is: ``django`` first, third-party packages alphabetically,
        ``project`` last.

        When ``genson`` is available, dict-valued fields with
        JSON-serialisable defaults are enriched: the annotation is
        updated (e.g. ``dict[str, Any]`` → ``dict[str, DatabasesEntry]``)
        and the corresponding ``TypedDict`` definition is emitted before
        the class body.

        Returns:
            A complete, ``ast.parse``-able Python source string.
        """
        # ---------------------------------------------------------------- #
        # Phase 1: collect genson-enriched annotations and TypedDict defs #
        # ---------------------------------------------------------------- #
        enriched_annotations: dict[str, str] = {}
        all_typeddict_defs: list[TypedDictDef] = []
        seen_class_names: set[str] = set()

        for f in self._fields:
            if (
                f.value_kind == ValueKind.STATIC
                and isinstance(f.default, dict)
                and f.default  # skip empty dicts
            ):
                try:
                    from django_aqueduct.codegen.dict_schema import (  # noqa: PLC0415
                        enrich_dict_annotation,
                    )

                    annotation, new_defs = enrich_dict_annotation(f.name, f.default)
                    if annotation != "dict[str, Any]":
                        if new_defs:
                            # TypedDict definitions — check for name conflicts
                            if not any(
                                d.class_name in seen_class_names for d in new_defs
                            ):
                                enriched_annotations[f.name] = annotation
                                all_typeddict_defs.extend(new_defs)
                                for d in new_defs:
                                    seen_class_names.add(d.class_name)
                        else:
                            # No TypedDicts but annotation is still richer
                            # (e.g. dict[str, str] for a homogeneous primitive dict)
                            enriched_annotations[f.name] = annotation
                except ImportError:
                    pass

        # ---------------------------------------------------------------- #
        # Phase 2: build the output string                                #
        # ---------------------------------------------------------------- #
        include_typeddict = bool(all_typeddict_defs)
        lines: list[str] = [_build_header(include_typeddict=include_typeddict)]

        # TypedDict class definitions
        if all_typeddict_defs:
            lines.append("\n")
            for td in all_typeddict_defs:
                lines.append(_render_typeddict(td))

        lines.append(_CLASS_OPEN)

        # ---------------------------------------------------------------- #
        # Phase 3: group fields and emit section bodies                   #
        # ---------------------------------------------------------------- #
        # Use owning_package when attribution has been run; fall back to
        # source_module for backward-compatible behaviour.
        use_package_groups = any(f.owning_package for f in self._fields)

        def _group_key(f: DiscoveredField) -> str:
            if use_package_groups:
                return f.owning_package or f.source_module
            return f.source_module

        def _group_sort_key(group_name: str) -> tuple[int, str]:
            """Django first, project last, rest alphabetically."""
            if group_name == "django":
                return (0, "")
            if group_name == "project":
                return (2, "")
            return (1, group_name)

        groups: dict[str, list[DiscoveredField]] = defaultdict(list)
        for f in self._fields:
            groups[_group_key(f)].append(f)

        for group_name in sorted(groups, key=_group_sort_key):
            module_fields = groups[group_name]
            lines.append(f"    # ===== {group_name} =====\n")
            for f in module_fields:
                annotation_override = enriched_annotations.get(f.name)
                lines.append(
                    _render_field(f, annotation_override=annotation_override) + "\n"
                )
            lines.append("\n")

        lines.append(_VALIDATOR_STUB)
        lines.append("\n")

        return "".join(lines)
