"""Pure IR → source renderer for codegen v2.

This renderer never imports the target module, never ``repr()``s a live
object, and never does string surgery on type annotations. It is a pure
function of
:class:`~django_aqueduct.discovery.ir.SettingField` IR, which makes golden-file
and determinism tests trivial.

Output is split into **managed** regions (rewritten on every run, fenced by
``# >>> aqueduct:generated:<id>`` / ``# <<< aqueduct:generated:<id>``) and
leaves room for **preserved** regions the writer keeps byte-for-byte. See
:mod:`django_aqueduct.codegen.regions` for the merge/`--check` writer.

The output is written to be ruff-clean (and ``ruff format``-stable) out of
the box under a standard ``select = ["E", "F", ...]`` config at the default
88-column line length: string literals prefer double quotes and any
``Field(...)``/decorator call that would exceed the line length is exploded
one-argument-per-line, matching what ``ruff format`` itself would produce —
so ``ruff format`` is a no-op on generated regions and doesn't fight
``--check``. There is no blanket ``# ruff: noqa``; a handful of long,
human-authored strings (descriptions, usage-mined comments) can still exceed
the line length, and those specific lines get a targeted
``# noqa: E501`` instead. If your project selects rules beyond the ~9 groups
this was validated against (e.g. ``Q``, ``COM``, ``ANN``, ``D`` on generated
code), the fallback is still to ``extend-exclude`` the generated file (or
just the regions your linter can't be taught to skip) in ``[tool.ruff]``.
"""

from __future__ import annotations

import re
from typing import TYPE_CHECKING

from django_aqueduct.discovery.ir import (
    DefaultStrategy,
    ImportSpec,
    SettingField,
    render_str_literal,
)

if TYPE_CHECKING:
    from django_aqueduct.codegen.dict_schema import TypedDictDef

_COMMENT_BLOCK = """\
# This file was generated by django-aqueduct (codegen v2).
# Regenerate with `manage.py generate_aqueduct_settings`.
#
# Code inside `# >>> aqueduct:generated:*` regions is overwritten on every run.
# Add validators and overrides inside `# >>> aqueduct:preserved:*` regions
# (or anywhere outside a generated region) — they survive regeneration.
"""

# Matches ``ruff format``'s own default (and this project's configured 88).
_LINE_LENGTH = 88

_ANY_RE = re.compile(r"\bAny\b")

# Framework imports every generated model needs, regardless of field shape.
# `Any` is deliberately excluded: several `TypeRef`s render as the bare `Any`
# base without declaring `typing.Any` in their own `.imports` (see
# discovery/static.py, discovery/enrich.py), relying on the renderer to add it
# — but only when some field's rendered output actually uses it, or it's an
# unused import (F401) the moment a model happens not to need `Any` anywhere.
_BASE_IMPORTS: frozenset[ImportSpec] = frozenset(
    {
        ImportSpec("pydantic", "Field"),
        ImportSpec("pydantic_settings", "BaseSettings"),
        ImportSpec("pydantic_settings", "SettingsConfigDict"),
    }
)


def region_open(kind: str, region_id: str) -> str:
    """Return the opening marker line for a region (no trailing newline)."""
    return f"    # >>> aqueduct:{kind}:{region_id}"


def region_close(kind: str, region_id: str) -> str:
    """Return the closing marker line for a region (no trailing newline)."""
    return f"    # <<< aqueduct:{kind}:{region_id}"


def _is_stdlib(module: str) -> bool:
    """Return True if *module*'s top-level package is in the standard library."""
    import sys  # noqa: PLC0415

    return module.split(".")[0] in sys.stdlib_module_names


def _render_import_section(specs: list[ImportSpec]) -> list[str]:
    """Render one isort-style section: plain ``import x`` then ``from x import y``.

    Mirrors ``ruff``'s own ``isort`` output for a single section (no blank
    line between the plain and ``from`` groups *within* a section — only
    between stdlib and non-stdlib sections, handled by the caller). An
    aliased name (``from m import a as b``) always renders on its own line so
    a comma-joined list never silently drops the alias.
    """
    from collections import defaultdict  # noqa: PLC0415

    lines: list[str] = []
    plain = sorted({s for s in specs if s.name is None}, key=lambda s: s.sort_key())
    for s in plain:
        lines.append(s.render())

    from_by_module: dict[str, set[str]] = defaultdict(set)
    aliased: list[ImportSpec] = []
    for s in specs:
        if s.name is None:
            continue
        if s.asname is not None:
            aliased.append(s)
        else:
            from_by_module[s.module].add(s.name)

    aliased_by_module: dict[str, list[ImportSpec]] = defaultdict(list)
    for s in sorted(aliased, key=lambda s: s.sort_key()):
        aliased_by_module[s.module].append(s)

    for module in sorted(set(from_by_module) | set(aliased_by_module)):
        if module in from_by_module:
            names = ", ".join(sorted(from_by_module[module]))
            lines.append(f"from {module} import {names}")
        for s in aliased_by_module.get(module, []):
            lines.append(s.render())
    return lines


def _render_imports(specs: frozenset[ImportSpec]) -> str:
    """Render a deterministic, ``ruff``/``isort``-clean, de-duplicated import block.

    ``from __future__`` is always first, then a standard-library section, then
    an everything-else (third-party) section — a blank line only between
    sections that are both non-empty, matching ``ruff format``'s isort output
    so it doesn't reorder this block (``I001``).
    """
    non_future = [s for s in specs if s.module != "__future__"]
    stdlib_lines = _render_import_section(
        [s for s in non_future if _is_stdlib(s.module)]
    )
    other_lines = _render_import_section(
        [s for s in non_future if not _is_stdlib(s.module)]
    )

    lines = ["from __future__ import annotations", ""]
    lines.extend(stdlib_lines)
    if stdlib_lines and other_lines:
        lines.append("")
    lines.extend(other_lines)
    return "\n".join(lines)


def _ordered_set(value: set[object]) -> list[object]:
    """Return *value*'s elements in a deterministic order.

    ``set`` iteration order depends on hash values, which for ``str`` members
    varies across process runs (hash randomization) — rendering a set in
    iteration order would make the generated file nondeterministic between
    runs, causing spurious ``--check`` drift. Sorting by ``(type name, repr)``
    (same key ``discovery/enrich.py`` uses for ``Literal[...]`` members)
    fixes an order regardless of hash seed, without requiring elements to be
    mutually comparable.
    """
    return sorted(value, key=lambda v: (type(v).__name__, repr(v)))


def _render_literal(value: object) -> str:
    """Render a literal default.

    The value originates from :func:`ast.literal_eval`, so it is one of
    str/bytes/int/float/bool/None/tuple/list/dict/set — every one of which has
    an ``eval``-safe representation requiring no imports. Strings containing
    ``<`` render as proper string literals (the v1 ``"<" in repr`` heuristic
    that nuked them is gone). Strings (including nested ones, inside
    list/tuple/dict/set) prefer double quotes to match ``ruff format``'s
    default — see :func:`~django_aqueduct.discovery.ir.render_str_literal`.
    ``set`` elements are rendered in a deterministic sorted order (see
    :func:`_ordered_set`) rather than repr()'s hash-order iteration.
    """
    if isinstance(value, str):
        return render_str_literal(value)
    if isinstance(value, list):
        return "[" + ", ".join(_render_literal(v) for v in value) + "]"
    if isinstance(value, tuple):
        inner = ", ".join(_render_literal(v) for v in value)
        return f"({inner},)" if len(value) == 1 else f"({inner})"
    if isinstance(value, dict):
        items = ", ".join(
            f"{_render_literal(k)}: {_render_literal(v)}" for k, v in value.items()
        )
        return "{" + items + "}"
    if isinstance(value, set):
        if not value:
            return "set()"
        return "{" + ", ".join(_render_literal(v) for v in _ordered_set(value)) + "}"
    return repr(value)


def _collection_brackets(
    value: list[object] | tuple[object, ...] | dict[object, object] | set[object],
) -> tuple[str, str]:
    if isinstance(value, list):
        return "[", "]"
    if isinstance(value, tuple):
        return "(", ")"
    return "{", "}"  # dict or set


def _render_collection_wrapped(value: object, indent: str, extra: int = 0) -> str:
    """Render *value* so it fits ``_LINE_LENGTH`` at *indent*, exploding if not.

    Mirrors ``ruff format``'s own collection-splitting — unlike a call's
    arguments (see :func:`_wrap_call`), a list/dict/tuple/set display has no
    "hug the items on one shared line" middle tier: once it doesn't fit flat,
    it goes straight to one item per line (recursively wrapped the same way),
    with a trailing comma — *unless* there's exactly one item, which (like a
    lone call argument) never gets a "magic" trailing comma. The one
    exception is a single-element *tuple*: ``(x,)``'s comma is semantically
    required (without it, ``(x)`` is just a parenthesized expression), so it
    is always kept. A ``set``'s items are rendered in the same deterministic
    order as :func:`_render_literal` (see :func:`_ordered_set`) rather than
    hash-order iteration, so this stays ``--check``-stable across runs.
    *extra* reserves columns already spoken for on the line (e.g. a ``key: ``
    prefix or a trailing comma).
    """
    single = _render_literal(value)
    if len(indent) + extra + len(single) <= _LINE_LENGTH or not isinstance(
        value, list | tuple | dict | set
    ):
        return single
    inner = f"{indent}    "
    open_b, close_b = _collection_brackets(value)
    if isinstance(value, dict):
        items = [
            f"{_render_literal(k)}: "
            f"{_render_collection_wrapped(v, inner, len(_render_literal(k)) + 3)}"
            for k, v in value.items()
        ]
    else:
        ordered = _ordered_set(value) if isinstance(value, set) else value
        items = [_render_collection_wrapped(v, inner) for v in ordered]
    if len(items) == 1:
        trailing_comma = "," if isinstance(value, tuple) else ""
        body = f"{inner}{items[0]}{trailing_comma}"
    else:
        body = "\n".join(f"{inner}{item}," for item in items)
    return f"{open_b}\n{body}\n{indent}{close_b}"


_LITERAL_KWARG_PREFIXES = ("default_factory=lambda: ", "default=")


def _reflow_long_literal_kwarg(rendered: str, literal: object) -> str:
    """Re-explode an overlong ``default=``/``default_factory=lambda: `` line.

    :func:`_wrap_call` only explodes at the level of ``Field(...)``'s own
    arguments; a single argument that is itself a large list/dict literal
    (e.g. a real ``DATABASES`` default) can still overflow on its own line.
    Reaching back into the source ``literal`` value (rather than re-parsing
    rendered text) lets us recursively explode just that one line with
    :func:`_render_collection_wrapped`, matching what ``ruff format`` would do.
    """
    lines = rendered.split("\n")
    for i, line in enumerate(lines):
        if len(line) <= _LINE_LENGTH:
            continue
        stripped = line.lstrip(" ")
        indent = line[: len(line) - len(stripped)]
        prefix = next(
            (p for p in _LITERAL_KWARG_PREFIXES if stripped.startswith(p)), None
        )
        if prefix is None:
            continue
        trail = "," if stripped.endswith(",") else ""
        wrapped = _render_collection_wrapped(
            literal, indent, extra=len(prefix) + len(trail)
        )
        lines[i] = f"{indent}{prefix}{wrapped}{trail}"
    return "\n".join(lines)


def _wrap_call(
    head: str, parts: list[str], trailer: str = "", indent: str = "    "
) -> str:
    """Render ``{head}({parts...}){trailer}``, matching ``ruff format``'s wrap.

    Black/ruff try, in order: (1) the whole call on one line; (2) the args
    moved inside the parens but still joined on one (indented) line, no
    trailing comma; (3) one argument per line with a trailing comma, closing
    paren on its own line. Each tier is only used if the previous one didn't
    fit within :data:`_LINE_LENGTH`.
    """
    single = f"{head}({', '.join(parts)}){trailer}"
    if len(single) <= _LINE_LENGTH or not parts:
        return single
    inner = f"{indent}    "
    joined = ", ".join(parts)
    if len(inner) + len(joined) <= _LINE_LENGTH:
        body = f"{inner}{joined}"
    else:
        body = "\n".join(f"{inner}{p}," for p in parts)
    return f"{head}(\n{body}\n{indent}){trailer}"


def _render_default_expr(f: SettingField) -> tuple[str, str]:
    """Return ``(field_default_kwarg, trailing_comment)`` for a field's default."""
    d = f.default
    if d.strategy is DefaultStrategy.REQUIRED:
        return "...", ""
    if d.strategy is DefaultStrategy.DERIVED:
        return (
            "default=None",
            "  # DERIVED: reproduce in a @model_validator (conditional/computed value)",
        )
    if d.strategy is DefaultStrategy.REDACTED:
        return (
            "default=None",
            "  # REDACTED: name looks secret-like — set via a source, not here",
        )
    if d.strategy is DefaultStrategy.RUNTIME_ONLY:
        return (
            "default=None",
            "  # RUNTIME-ONLY: observed at runtime, no static assignment found"
            " — review and set explicitly",
        )
    if d.strategy is DefaultStrategy.EXPR:
        return f"default_factory=lambda: {d.expr}", ""
    if d.strategy is DefaultStrategy.FACTORY:
        return f"default_factory=lambda: {_render_literal(d.literal)}", ""
    # LITERAL
    return f"default={_render_literal(d.literal)}", ""


def _render_typeddict(td: TypedDictDef) -> str:
    """Render a ``TypedDict`` class definition (``total=False``) as source."""
    lines = [
        f"class {td.class_name}(TypedDict, total=False):",
        '    """Genson-inferred shape for a dict-valued setting."""',
        "",
    ]
    if not td.fields:
        lines.append("    pass")
    else:
        for field in td.fields:
            lines.append(f"    {field.name}: {field.annotation}")
    return "\n".join(lines) + "\n"


def _container_kind(base: str) -> str | None:
    """Return ``"list"``/``"dict"`` for a container base type, else ``None``.

    ``pydantic-settings`` json-decodes any complex-typed field's env value by
    default, which fails for the non-JSON list/dict formats real env vars
    actually use (comma-separated, Python-literal, crontab strings, ...).
    Fields with these bases get a ``NoDecode`` annotation plus a
    ``field_validator`` that parses them instead.
    """
    if base.startswith("list["):
        return "list"
    if base.startswith("dict["):
        return "dict"
    return None


def _render_field(
    f: SettingField,
    annotation_override: str | None = None,
    *,
    no_decode: bool = False,
) -> str:
    """Render one field as a Pydantic ``Field`` declaration (indented, no newline).

    ``annotation_override`` supplies a genson-enriched annotation (e.g.
    ``dict[str, DatabasesEntry]``) in place of the IR's ``dict[str, Any]``.
    ``no_decode`` wraps the annotation in ``Annotated[..., NoDecode]`` so the
    corresponding ``field_validator`` (see
    :meth:`ModelRenderer._render_container_decoders`) receives the raw env
    string instead of a ``json.loads`` failure.
    """
    default_kwarg, comment = _render_default_expr(f)

    # A `default=None` is only valid if the annotation accepts None. Widen at
    # render time (regardless of which producer built the IR) so a field that
    # renders None never raises a ValidationError when None is supplied.
    type_ref = f.type
    if default_kwarg == "default=None" and not type_ref.optional:
        type_ref = type_ref.with_optional()
    annotation = annotation_override or type_ref.render()
    if no_decode:
        annotation = f"Annotated[{annotation}, NoDecode]"

    parts = [default_kwarg]
    if f.env_aliases:
        choices = ", ".join(render_str_literal(a) for a in f.env_aliases)
        parts.append(f"validation_alias=AliasChoices({choices})")
    for bound in ("gt", "ge", "lt", "le"):
        value = getattr(f.constraints, bound)
        if value is not None:
            parts.append(f"{bound}={value!r}")
    if f.description:
        parts.append(f"description={render_str_literal(f.description)}")

    if f.type.needs_refinement:
        comment = comment or "  # TODO: refine type"
    if not f.constraints.is_empty():
        comment = (
            f"{comment}  # usage-mined bound(s) — confirm before trusting"
            if comment
            else "  # usage-mined bound(s) — confirm before trusting"
        )
    dev = "  # dev-only" if f.dev_only else ""
    trailer = f"{comment}{dev}"
    rendered = _wrap_call(f"    {f.name}: {annotation} = Field", parts, trailer)
    if f.default.strategy in (
        DefaultStrategy.FACTORY,
        DefaultStrategy.LITERAL,
    ) and isinstance(f.default.literal, list | tuple | dict | set):
        rendered = _reflow_long_literal_kwarg(rendered, f.default.literal)
    return _suppress_unwrappable_overflow(rendered)


def _suppress_unwrappable_overflow(rendered: str) -> str:
    """Append a targeted ``# noqa: E501`` to any physical line that still overflows.

    Exploding a call one-argument-per-line (see :func:`_wrap_call`) can't help
    when the overflow comes from a long human-authored string (a description,
    a usage-mined comment) rather than from the call's shape — ``ruff format``
    can't shrink that either, on the exploded ``description=...,`` line or on
    a single-line field's trailing comment. Rather than a blanket file-level
    suppression, flag only the specific line(s), with the specific code they
    would trip.
    """
    lines = rendered.split("\n")
    return "\n".join(
        f"{line}  # noqa: E501"
        if len(line) > _LINE_LENGTH and "noqa" not in line
        else line
        for line in lines
    )


class ModelRenderer:
    """Render a list of :class:`SettingField` IR into a settings model module.

    Args:
        fields: The IR fields to render.
        class_name: Name of the generated ``BaseSettings`` subclass.
    """

    def __init__(
        self,
        fields: list[SettingField],
        *,
        class_name: str = "AqueductSettings",
        extra: str = "allow",
        dict_enrichment: dict[str, tuple[str, list[TypedDictDef]]] | None = None,
    ) -> None:
        """Store the fields, class name, and model ``extra`` strictness.

        Args:
            fields: The IR fields to render.
            class_name: Name of the generated ``BaseSettings`` subclass.
            extra: Pydantic ``extra`` policy — ``"allow"`` (tolerate & keep
                un-modeled keys), ``"ignore"`` (drop them), or ``"forbid"``
                (reject them, enabling typo detection).
            dict_enrichment: Precomputed ``{field_name: (annotation,
                typeddict_defs)}`` overlay, e.g. from
                :mod:`~django_aqueduct.discovery.runtime`'s multi-sample
                genson enrichment. Takes precedence over this renderer's own
                literal-default enrichment for the same field name — it can
                refine fields (``DERIVED``/``Any``) whose default was never
                a literal dict, which the renderer alone cannot do without
                importing the target module.
        """
        if extra not in ("allow", "ignore", "forbid"):
            raise ValueError(f"extra must be allow/ignore/forbid, got {extra!r}")
        self._fields = fields
        self._class_name = class_name
        self._dict_enrichment = dict_enrichment or {}
        self._extra = extra

    def _render_grouped_fields(
        self, enriched: dict[str, str], no_decode_names: set[str]
    ) -> list[str]:
        """Render fields grouped by owning package (or source module) with headers.

        Groups are ordered django-first, project-last, everything else
        alphabetically — matching the v1 generator's provenance sections. When
        no field carries an ``owning_package`` and every field shares one
        source module, a single unlabelled block is emitted (no header noise).
        """
        from collections import defaultdict  # noqa: PLC0415

        use_package = any(f.owning_package for f in self._fields)

        def group_of(f: SettingField) -> str:
            if use_package:
                return f.owning_package or f.provenance.source_module
            return f.provenance.source_module

        groups: dict[str, list[SettingField]] = defaultdict(list)
        for f in self._fields:
            groups[group_of(f)].append(f)

        def group_sort_key(name: str) -> tuple[int, str]:
            if name == "django":
                return (0, "")
            if name == "project":
                return (2, "")
            return (1, name)

        # A single group with no package attribution needs no header.
        emit_headers = use_package or len(groups) > 1

        out: list[str] = []
        for group_name in sorted(groups, key=group_sort_key):
            if emit_headers:
                out.append(f"    # ===== {group_name} =====")
            for f in groups[group_name]:
                out.append(
                    _render_field(
                        f,
                        enriched.get(f.name),
                        no_decode=f.name in no_decode_names,
                    )
                )
        return out

    def _container_fields(
        self, enriched: dict[str, str]
    ) -> tuple[list[str], list[str]]:
        """Return ``(list_field_names, dict_field_names)`` sorted alphabetically.

        Uses the *rendered* base (post genson-enrichment) so an enriched
        ``dict[str, DatabasesEntry]`` is still recognised as a dict.
        """
        list_fields: list[str] = []
        dict_fields: list[str] = []
        for f in self._fields:
            kind = _container_kind(enriched.get(f.name, f.type.base))
            if kind == "list":
                list_fields.append(f.name)
            elif kind == "dict":
                dict_fields.append(f.name)
        return sorted(list_fields), sorted(dict_fields)

    def _render_container_decoders(
        self, list_fields: list[str], dict_fields: list[str]
    ) -> list[str]:
        """Render ``field_validator``s that parse env strings for containers.

        ``pydantic-settings`` json-decodes any complex-typed field's env
        value by default, which already handles genuine JSON (``[true,
        false]``, ``{"a": null}``); real env vars also feed list/dict
        settings as comma-separated or Python-literal strings (this is
        exactly what the mitol ``EnvParser`` list/crontab helpers produce),
        which raise ``SettingsError`` before the model ever instantiates.
        Paired with the ``NoDecode`` annotation on each field (see
        ``_render_field``), these validators receive the raw string and try
        ``json.loads`` first (so JSON inputs keep working exactly as
        before), then ``ast.literal_eval`` (Python-literal strings, e.g.
        single-quoted), then — lists only — a final comma-split fallback.
        """
        lines: list[str] = []
        if list_fields:
            names = [render_str_literal(name) for name in list_fields]
            lines.append(_wrap_call("    @field_validator", [*names, 'mode="before"']))
            lines.append("    @classmethod")
            lines.append(
                "    def _aqueduct_decode_list_fields(cls, value: object) -> object:"
            )
            lines.append(
                '        """Parse a list from a JSON, Python-literal, or '
                'comma-separated env string."""'
            )
            lines.append("        if not isinstance(value, str):")
            lines.append("            return value")
            lines.append("        try:")
            lines.append("            parsed = json.loads(value)")
            lines.append("        except (ValueError, TypeError):")
            lines.append("            try:")
            lines.append("                parsed = ast.literal_eval(value)")
            lines.append("            except (ValueError, SyntaxError):")
            lines.append("                parsed = None")
            lines.append("        if isinstance(parsed, list):")
            lines.append("            return parsed")
            lines.append('        return [item.strip() for item in value.split(",")]')
            if dict_fields:
                lines.append("")
        if dict_fields:
            names = [render_str_literal(name) for name in dict_fields]
            lines.append(_wrap_call("    @field_validator", [*names, 'mode="before"']))
            lines.append("    @classmethod")
            lines.append(
                "    def _aqueduct_decode_dict_fields(cls, value: object) -> object:"
            )
            lines.append(
                '        """Parse a dict from a JSON or Python-literal env string."""'
            )
            lines.append("        if not isinstance(value, str):")
            lines.append("            return value")
            lines.append("        try:")
            lines.append("            parsed = json.loads(value)")
            lines.append("        except (ValueError, TypeError):")
            lines.append("            parsed = None")
            lines.append("        if isinstance(parsed, dict):")
            lines.append("            return parsed")
            lines.append("        return ast.literal_eval(value)")
        return lines

    def _enrich_dicts(self) -> tuple[dict[str, str], list[TypedDictDef]]:
        """Return ``(enriched_annotations, typeddict_defs)`` for dict-valued fields.

        Uses genson (via ``dict_schema.enrich_dict_annotation``) to turn a
        ``dict[str, Any]`` literal into a precise ``dict[str, XxxEntry]`` plus
        the ``TypedDict`` definitions. Silently no-ops when genson is not
        installed (the ``[codegen]`` extra) or a value is not enrichable.

        Externally supplied ``dict_enrichment`` (see ``__init__``) is applied
        first and takes precedence per field name — it was already computed
        upstream (genson need not be importable *here* for it to apply).
        """
        enriched: dict[str, str] = {}
        defs: list[TypedDictDef] = []
        seen: set[str] = set()

        for name, (annotation, new_defs) in self._dict_enrichment.items():
            if annotation == "dict[str, Any]":
                continue
            if any(d.class_name in seen for d in new_defs):
                continue
            enriched[name] = annotation
            for d in new_defs:
                seen.add(d.class_name)
            defs.extend(new_defs)

        try:
            from django_aqueduct.codegen.dict_schema import (  # noqa: PLC0415
                enrich_dict_annotation,
            )
        except ImportError:
            return enriched, defs

        literal_kinds = (DefaultStrategy.LITERAL, DefaultStrategy.FACTORY)
        for f in self._fields:
            if f.name in enriched:
                continue
            if f.default.strategy not in literal_kinds:
                continue
            if not isinstance(f.default.literal, dict) or not f.default.literal:
                continue
            annotation, new_defs = enrich_dict_annotation(f.name, f.default.literal)
            if annotation == "dict[str, Any]":
                continue
            # Skip if a TypedDict name would collide with an already-emitted one.
            if any(d.class_name in seen for d in new_defs):
                continue
            enriched[f.name] = annotation
            for d in new_defs:
                seen.add(d.class_name)
            defs.extend(new_defs)
        return enriched, defs

    def _all_imports(self, *, has_containers: bool = False) -> frozenset[ImportSpec]:
        specs: set[ImportSpec] = set(_BASE_IMPORTS)
        if any(f.env_aliases for f in self._fields):
            specs.add(ImportSpec("pydantic", "AliasChoices"))
        if has_containers:
            specs.add(ImportSpec("ast"))
            specs.add(ImportSpec("json"))
            specs.add(ImportSpec("typing", "Annotated"))
            specs.add(ImportSpec("pydantic", "field_validator"))
            specs.add(ImportSpec("pydantic_settings", "NoDecode"))
        for f in self._fields:
            specs |= f.all_imports()
        return frozenset(specs)

    def render(self) -> str:
        """Return the complete generated module as a string."""
        enriched, typeddict_defs = self._enrich_dicts()
        list_fields, dict_fields = self._container_fields(enriched)
        no_decode_names = set(list_fields) | set(dict_fields)

        field_lines = self._render_grouped_fields(enriched, no_decode_names)
        container_lines = (
            self._render_container_decoders(list_fields, dict_fields)
            if (list_fields or dict_fields)
            else []
        )
        # 2 blank lines between top-level class defs (Black/ruff-format style).
        typeddict_blocks = [_render_typeddict(td).rstrip("\n") for td in typeddict_defs]
        typeddict_lines = (
            "\n\n\n".join(typeddict_blocks).split("\n") if typeddict_blocks else []
        )

        specs = set(self._all_imports(has_containers=bool(list_fields or dict_fields)))
        # Check the actual annotations (not the rendered lines) for `Any` — a
        # rendered line can also contain "Any" inside a description/comment
        # (e.g. `description="Can be Any value"`), which would otherwise
        # trigger an unnecessary (and F401-flagged) `Any` import.
        has_any = any(
            _ANY_RE.search(enriched.get(f.name) or f.type.render())
            for f in self._fields
        ) or any(
            _ANY_RE.search(field.annotation)
            for td in typeddict_defs
            for field in td.fields
        )
        if has_any:
            specs.add(ImportSpec("typing", "Any"))
        if typeddict_defs:
            specs.add(ImportSpec("typing", "TypedDict"))
        imports = _render_imports(frozenset(specs))

        lines: list[str] = []
        lines.append(_COMMENT_BLOCK)
        lines.append("")
        lines.append(region_open("generated", "imports").lstrip())
        lines.append(imports)
        lines.append("")  # ruff-format/isort wants a blank line before the marker
        lines.append(region_close("generated", "imports").lstrip())
        lines.append("")
        lines.append("")
        if typeddict_defs:
            lines.append(region_open("generated", "typeddicts").lstrip())
            lines.extend(typeddict_lines)
            # Black/ruff-format want 2 blank lines after a top-level class.
            lines.append("")
            lines.append("")
            lines.append(region_close("generated", "typeddicts").lstrip())
            lines.append("")
            lines.append("")
        docstring = (
            '    """Typed Django settings model generated by django-aqueduct."""'
        )
        config_line = (
            f"    model_config = SettingsConfigDict("
            f'env_prefix="", extra="{self._extra}")'
        )
        lines.append(f"class {self._class_name}(BaseSettings):")
        lines.append(docstring)
        lines.append("")
        lines.append(config_line)
        lines.append("")
        lines.append(region_open("generated", "fields"))
        lines.extend(field_lines)
        lines.append(region_close("generated", "fields"))
        lines.append("")
        if list_fields or dict_fields:
            lines.append(region_open("generated", "container_decoders"))
            lines.extend(container_lines)
            lines.append("")  # ruff-format wants a blank line after a method body
            lines.append(region_close("generated", "container_decoders"))
            lines.append("")
        lines.append(region_open("preserved", "validators"))
        lines.append("    # Add @model_validator / @field_validator methods here.")
        lines.append("    # This region is preserved across regeneration.")
        lines.append(region_close("preserved", "validators"))
        lines.append("")
        return "\n".join(lines)
