"""Pure IR → source renderer for codegen v2.

This renderer never imports the target module, never ``repr()``s a live
object, and never does string surgery on type annotations. It is a pure
function of
:class:`~django_aqueduct.discovery.ir.SettingField` IR, which makes golden-file
and determinism tests trivial.

Output is split into **managed** regions (rewritten on every run, fenced by
``# >>> aqueduct:generated:<id>`` / ``# <<< aqueduct:generated:<id>``) and
leaves room for **preserved** regions the writer keeps byte-for-byte. See
:mod:`django_aqueduct.codegen.regions` for the merge/`--check` writer.
"""

from __future__ import annotations

from django_aqueduct.discovery.ir import (
    DefaultStrategy,
    ImportSpec,
    SettingField,
)

_COMMENT_BLOCK = """\
# ruff: noqa
# This file was generated by django-aqueduct (codegen v2).
# Regenerate with `manage.py generate_aqueduct_settings`.
#
# Code inside `# >>> aqueduct:generated:*` regions is overwritten on every run.
# Add validators and overrides inside `# >>> aqueduct:preserved:*` regions
# (or anywhere outside a generated region) — they survive regeneration.
"""

# Framework imports every generated model needs.
_BASE_IMPORTS: frozenset[ImportSpec] = frozenset(
    {
        ImportSpec("typing", "Any"),
        ImportSpec("pydantic", "Field"),
        ImportSpec("pydantic_settings", "BaseSettings"),
        ImportSpec("pydantic_settings", "SettingsConfigDict"),
    }
)


def region_open(kind: str, region_id: str) -> str:
    """Return the opening marker line for a region (no trailing newline)."""
    return f"    # >>> aqueduct:{kind}:{region_id}"


def region_close(kind: str, region_id: str) -> str:
    """Return the closing marker line for a region (no trailing newline)."""
    return f"    # <<< aqueduct:{kind}:{region_id}"


def _render_imports(specs: frozenset[ImportSpec]) -> str:
    """Render a deterministic, de-duplicated import block.

    ``import x`` lines come first (sorted); ``from x import a, b`` lines follow,
    grouped by module with names sorted. ``from __future__`` is always first.
    """
    # Plain `import x` / `import x as y`.
    plain = sorted({s for s in specs if s.name is None}, key=lambda s: s.sort_key())
    # `from m import a, b` — only merge un-aliased names onto one line; an
    # aliased name (`from m import a as b`) renders on its own line so the
    # alias is not lost in a comma-joined list.
    from_by_module: dict[str, set[str]] = {}
    aliased: list[ImportSpec] = []
    for s in specs:
        if s.name is None or s.module == "__future__":
            continue
        if s.asname is not None:
            aliased.append(s)
        else:
            from_by_module.setdefault(s.module, set()).add(s.name)

    lines = ["from __future__ import annotations", ""]
    for s in plain:
        lines.append(s.render())
    if plain:
        lines.append("")
    for module in sorted(from_by_module):
        names = ", ".join(sorted(from_by_module[module]))
        lines.append(f"from {module} import {names}")
    for s in sorted(aliased, key=lambda s: s.sort_key()):
        lines.append(s.render())
    return "\n".join(lines)


def _render_literal(value: object) -> str:
    """Render a literal default.

    The value originates from :func:`ast.literal_eval`, so it is one of
    str/bytes/int/float/bool/None/tuple/list/dict/set — every one of which has
    an ``eval``-safe ``repr`` requiring no imports. Strings containing ``<``
    render as proper string literals (the v1 ``"<" in repr`` heuristic that
    nuked them is gone).
    """
    return repr(value)


def _render_default_expr(f: SettingField) -> tuple[str, str]:
    """Return ``(field_default_kwarg, trailing_comment)`` for a field's default."""
    d = f.default
    if d.strategy is DefaultStrategy.REQUIRED:
        return "...", ""
    if d.strategy is DefaultStrategy.DERIVED:
        return (
            "default=None",
            "  # DERIVED: reproduce in a @model_validator (conditional/computed value)",
        )
    if d.strategy is DefaultStrategy.REDACTED:
        return (
            "default=None",
            "  # REDACTED: name looks secret-like — set via a source, not here",
        )
    if d.strategy is DefaultStrategy.EXPR:
        return f"default_factory=lambda: {d.expr}", ""
    if d.strategy is DefaultStrategy.FACTORY:
        return f"default_factory=lambda: {_render_literal(d.literal)}", ""
    # LITERAL
    return f"default={_render_literal(d.literal)}", ""


def _render_field(f: SettingField) -> str:
    """Render one field as a Pydantic ``Field`` declaration (indented, no newline)."""
    default_kwarg, comment = _render_default_expr(f)

    # A `default=None` is only valid if the annotation accepts None. Widen at
    # render time (regardless of which producer built the IR) so a field that
    # renders None never raises a ValidationError when None is supplied.
    type_ref = f.type
    if default_kwarg == "default=None" and not type_ref.optional:
        type_ref = type_ref.with_optional()
    annotation = type_ref.render()

    parts = [default_kwarg]
    if f.env_aliases:
        choices = ", ".join(repr(a) for a in f.env_aliases)
        parts.append(f"validation_alias=AliasChoices({choices})")
    if f.description:
        parts.append(f"description={f.description!r}")

    field_call = f"Field({', '.join(parts)})"
    if f.type.needs_refinement:
        comment = comment or "  # TODO: refine type"
    dev = "  # dev-only" if f.dev_only else ""
    return f"    {f.name}: {annotation} = {field_call}{comment}{dev}"


class ModelRenderer:
    """Render a list of :class:`SettingField` IR into a settings model module.

    Args:
        fields: The IR fields to render.
        class_name: Name of the generated ``BaseSettings`` subclass.
    """

    def __init__(
        self, fields: list[SettingField], *, class_name: str = "AqueductSettings"
    ) -> None:
        """Store the fields and target class name to render."""
        self._fields = fields
        self._class_name = class_name

    def _render_grouped_fields(self) -> list[str]:
        """Render fields grouped by owning package (or source module) with headers.

        Groups are ordered django-first, project-last, everything else
        alphabetically — matching the v1 generator's provenance sections. When
        no field carries an ``owning_package`` and every field shares one
        source module, a single unlabelled block is emitted (no header noise).
        """
        from collections import defaultdict  # noqa: PLC0415

        use_package = any(f.owning_package for f in self._fields)

        def group_of(f: SettingField) -> str:
            if use_package:
                return f.owning_package or f.provenance.source_module
            return f.provenance.source_module

        groups: dict[str, list[SettingField]] = defaultdict(list)
        for f in self._fields:
            groups[group_of(f)].append(f)

        def group_sort_key(name: str) -> tuple[int, str]:
            if name == "django":
                return (0, "")
            if name == "project":
                return (2, "")
            return (1, name)

        # A single group with no package attribution needs no header.
        emit_headers = use_package or len(groups) > 1

        out: list[str] = []
        for group_name in sorted(groups, key=group_sort_key):
            if emit_headers:
                out.append(f"    # ===== {group_name} =====")
            for f in groups[group_name]:
                out.append(_render_field(f))
        return out

    def _all_imports(self) -> frozenset[ImportSpec]:
        specs: set[ImportSpec] = set(_BASE_IMPORTS)
        if any(f.env_aliases for f in self._fields):
            specs.add(ImportSpec("pydantic", "AliasChoices"))
        for f in self._fields:
            specs |= f.all_imports()
        return frozenset(specs)

    def render(self) -> str:
        """Return the complete generated module as a string."""
        imports = _render_imports(self._all_imports())

        lines: list[str] = []
        lines.append(_COMMENT_BLOCK)
        lines.append("")
        lines.append(region_open("generated", "imports").lstrip())
        lines.append(imports)
        lines.append(region_close("generated", "imports").lstrip())
        lines.append("")
        lines.append("")
        docstring = (
            '    """Typed Django settings model generated by django-aqueduct."""'
        )
        config_line = (
            '    model_config = SettingsConfigDict(env_prefix="", extra="allow")'
        )
        lines.append(f"class {self._class_name}(BaseSettings):")
        lines.append(docstring)
        lines.append("")
        lines.append(config_line)
        lines.append("")
        lines.append(region_open("generated", "fields"))
        lines.extend(self._render_grouped_fields())
        lines.append(region_close("generated", "fields"))
        lines.append("")
        lines.append(region_open("preserved", "validators"))
        lines.append("    # Add @model_validator / @field_validator methods here.")
        lines.append("    # This region is preserved across regeneration.")
        lines.append(region_close("preserved", "validators"))
        lines.append("")
        return "\n".join(lines)
