"""Pure IR → source renderer for codegen v2.

This renderer never imports the target module, never ``repr()``s a live
object, and never does string surgery on type annotations. It is a pure
function of
:class:`~django_aqueduct.discovery.ir.SettingField` IR, which makes golden-file
and determinism tests trivial.

Output is split into **managed** regions (rewritten on every run, fenced by
``# >>> aqueduct:generated:<id>`` / ``# <<< aqueduct:generated:<id>``) and
leaves room for **preserved** regions the writer keeps byte-for-byte. See
:mod:`django_aqueduct.codegen.regions` for the merge/`--check` writer.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

from django_aqueduct.discovery.ir import (
    DefaultStrategy,
    ImportSpec,
    SettingField,
)

if TYPE_CHECKING:
    from django_aqueduct.codegen.dict_schema import TypedDictDef

_COMMENT_BLOCK = """\
# ruff: noqa
# This file was generated by django-aqueduct (codegen v2).
# Regenerate with `manage.py generate_aqueduct_settings`.
#
# Code inside `# >>> aqueduct:generated:*` regions is overwritten on every run.
# Add validators and overrides inside `# >>> aqueduct:preserved:*` regions
# (or anywhere outside a generated region) — they survive regeneration.
"""

# Framework imports every generated model needs.
_BASE_IMPORTS: frozenset[ImportSpec] = frozenset(
    {
        ImportSpec("typing", "Any"),
        ImportSpec("pydantic", "Field"),
        ImportSpec("pydantic_settings", "BaseSettings"),
        ImportSpec("pydantic_settings", "SettingsConfigDict"),
    }
)


def region_open(kind: str, region_id: str) -> str:
    """Return the opening marker line for a region (no trailing newline)."""
    return f"    # >>> aqueduct:{kind}:{region_id}"


def region_close(kind: str, region_id: str) -> str:
    """Return the closing marker line for a region (no trailing newline)."""
    return f"    # <<< aqueduct:{kind}:{region_id}"


def _render_imports(specs: frozenset[ImportSpec]) -> str:
    """Render a deterministic, de-duplicated import block.

    ``import x`` lines come first (sorted); ``from x import a, b`` lines follow,
    grouped by module with names sorted. ``from __future__`` is always first.
    """
    # Plain `import x` / `import x as y`.
    plain = sorted({s for s in specs if s.name is None}, key=lambda s: s.sort_key())
    # `from m import a, b` — only merge un-aliased names onto one line; an
    # aliased name (`from m import a as b`) renders on its own line so the
    # alias is not lost in a comma-joined list.
    from_by_module: dict[str, set[str]] = {}
    aliased: list[ImportSpec] = []
    for s in specs:
        if s.name is None or s.module == "__future__":
            continue
        if s.asname is not None:
            aliased.append(s)
        else:
            from_by_module.setdefault(s.module, set()).add(s.name)

    lines = ["from __future__ import annotations", ""]
    for s in plain:
        lines.append(s.render())
    if plain:
        lines.append("")
    for module in sorted(from_by_module):
        names = ", ".join(sorted(from_by_module[module]))
        lines.append(f"from {module} import {names}")
    for s in sorted(aliased, key=lambda s: s.sort_key()):
        lines.append(s.render())
    return "\n".join(lines)


def _render_literal(value: object) -> str:
    """Render a literal default.

    The value originates from :func:`ast.literal_eval`, so it is one of
    str/bytes/int/float/bool/None/tuple/list/dict/set — every one of which has
    an ``eval``-safe ``repr`` requiring no imports. Strings containing ``<``
    render as proper string literals (the v1 ``"<" in repr`` heuristic that
    nuked them is gone).
    """
    return repr(value)


def _render_default_expr(f: SettingField) -> tuple[str, str]:
    """Return ``(field_default_kwarg, trailing_comment)`` for a field's default."""
    d = f.default
    if d.strategy is DefaultStrategy.REQUIRED:
        return "...", ""
    if d.strategy is DefaultStrategy.DERIVED:
        return (
            "default=None",
            "  # DERIVED: reproduce in a @model_validator (conditional/computed value)",
        )
    if d.strategy is DefaultStrategy.REDACTED:
        return (
            "default=None",
            "  # REDACTED: name looks secret-like — set via a source, not here",
        )
    if d.strategy is DefaultStrategy.RUNTIME_ONLY:
        return (
            "default=None",
            "  # RUNTIME-ONLY: observed at runtime, no static assignment found"
            " — review and set explicitly",
        )
    if d.strategy is DefaultStrategy.EXPR:
        return f"default_factory=lambda: {d.expr}", ""
    if d.strategy is DefaultStrategy.FACTORY:
        return f"default_factory=lambda: {_render_literal(d.literal)}", ""
    # LITERAL
    return f"default={_render_literal(d.literal)}", ""


def _render_typeddict(td: TypedDictDef) -> str:
    """Render a ``TypedDict`` class definition (``total=False``) as source."""
    lines = [f"class {td.class_name}(TypedDict, total=False):"]
    if not td.fields:
        lines.append("    pass")
    else:
        for field in td.fields:
            lines.append(f"    {field.name}: {field.annotation}")
    return "\n".join(lines) + "\n"


def _container_kind(base: str) -> str | None:
    """Return ``"list"``/``"dict"`` for a container base type, else ``None``.

    ``pydantic-settings`` json-decodes any complex-typed field's env value by
    default, which fails for the non-JSON list/dict formats real env vars
    actually use (comma-separated, Python-literal, crontab strings, ...).
    Fields with these bases get a ``NoDecode`` annotation plus a
    ``field_validator`` that parses them instead.
    """
    if base.startswith("list["):
        return "list"
    if base.startswith("dict["):
        return "dict"
    return None


def _render_field(
    f: SettingField,
    annotation_override: str | None = None,
    *,
    no_decode: bool = False,
) -> str:
    """Render one field as a Pydantic ``Field`` declaration (indented, no newline).

    ``annotation_override`` supplies a genson-enriched annotation (e.g.
    ``dict[str, DatabasesEntry]``) in place of the IR's ``dict[str, Any]``.
    ``no_decode`` wraps the annotation in ``Annotated[..., NoDecode]`` so the
    corresponding ``field_validator`` (see
    :meth:`ModelRenderer._render_container_decoders`) receives the raw env
    string instead of a ``json.loads`` failure.
    """
    default_kwarg, comment = _render_default_expr(f)

    # A `default=None` is only valid if the annotation accepts None. Widen at
    # render time (regardless of which producer built the IR) so a field that
    # renders None never raises a ValidationError when None is supplied.
    type_ref = f.type
    if default_kwarg == "default=None" and not type_ref.optional:
        type_ref = type_ref.with_optional()
    annotation = annotation_override or type_ref.render()
    if no_decode:
        annotation = f"Annotated[{annotation}, NoDecode]"

    parts = [default_kwarg]
    if f.env_aliases:
        choices = ", ".join(repr(a) for a in f.env_aliases)
        parts.append(f"validation_alias=AliasChoices({choices})")
    for bound in ("gt", "ge", "lt", "le"):
        value = getattr(f.constraints, bound)
        if value is not None:
            parts.append(f"{bound}={value!r}")
    if f.description:
        parts.append(f"description={f.description!r}")

    field_call = f"Field({', '.join(parts)})"
    if f.type.needs_refinement:
        comment = comment or "  # TODO: refine type"
    if not f.constraints.is_empty():
        comment = (
            f"{comment}  # usage-mined bound(s) — confirm before trusting"
            if comment
            else "  # usage-mined bound(s) — confirm before trusting"
        )
    dev = "  # dev-only" if f.dev_only else ""
    return f"    {f.name}: {annotation} = {field_call}{comment}{dev}"


class ModelRenderer:
    """Render a list of :class:`SettingField` IR into a settings model module.

    Args:
        fields: The IR fields to render.
        class_name: Name of the generated ``BaseSettings`` subclass.
    """

    def __init__(
        self,
        fields: list[SettingField],
        *,
        class_name: str = "AqueductSettings",
        extra: str = "allow",
        dict_enrichment: dict[str, tuple[str, list[TypedDictDef]]] | None = None,
    ) -> None:
        """Store the fields, class name, and model ``extra`` strictness.

        Args:
            fields: The IR fields to render.
            class_name: Name of the generated ``BaseSettings`` subclass.
            extra: Pydantic ``extra`` policy — ``"allow"`` (tolerate & keep
                un-modeled keys), ``"ignore"`` (drop them), or ``"forbid"``
                (reject them, enabling typo detection).
            dict_enrichment: Precomputed ``{field_name: (annotation,
                typeddict_defs)}`` overlay, e.g. from
                :mod:`~django_aqueduct.discovery.runtime`'s multi-sample
                genson enrichment. Takes precedence over this renderer's own
                literal-default enrichment for the same field name — it can
                refine fields (``DERIVED``/``Any``) whose default was never
                a literal dict, which the renderer alone cannot do without
                importing the target module.
        """
        if extra not in ("allow", "ignore", "forbid"):
            raise ValueError(f"extra must be allow/ignore/forbid, got {extra!r}")
        self._fields = fields
        self._class_name = class_name
        self._dict_enrichment = dict_enrichment or {}
        self._extra = extra

    def _render_grouped_fields(
        self, enriched: dict[str, str], no_decode_names: set[str]
    ) -> list[str]:
        """Render fields grouped by owning package (or source module) with headers.

        Groups are ordered django-first, project-last, everything else
        alphabetically — matching the v1 generator's provenance sections. When
        no field carries an ``owning_package`` and every field shares one
        source module, a single unlabelled block is emitted (no header noise).
        """
        from collections import defaultdict  # noqa: PLC0415

        use_package = any(f.owning_package for f in self._fields)

        def group_of(f: SettingField) -> str:
            if use_package:
                return f.owning_package or f.provenance.source_module
            return f.provenance.source_module

        groups: dict[str, list[SettingField]] = defaultdict(list)
        for f in self._fields:
            groups[group_of(f)].append(f)

        def group_sort_key(name: str) -> tuple[int, str]:
            if name == "django":
                return (0, "")
            if name == "project":
                return (2, "")
            return (1, name)

        # A single group with no package attribution needs no header.
        emit_headers = use_package or len(groups) > 1

        out: list[str] = []
        for group_name in sorted(groups, key=group_sort_key):
            if emit_headers:
                out.append(f"    # ===== {group_name} =====")
            for f in groups[group_name]:
                out.append(
                    _render_field(
                        f,
                        enriched.get(f.name),
                        no_decode=f.name in no_decode_names,
                    )
                )
        return out

    def _container_fields(
        self, enriched: dict[str, str]
    ) -> tuple[list[str], list[str]]:
        """Return ``(list_field_names, dict_field_names)`` sorted alphabetically.

        Uses the *rendered* base (post genson-enrichment) so an enriched
        ``dict[str, DatabasesEntry]`` is still recognised as a dict.
        """
        list_fields: list[str] = []
        dict_fields: list[str] = []
        for f in self._fields:
            kind = _container_kind(enriched.get(f.name, f.type.base))
            if kind == "list":
                list_fields.append(f.name)
            elif kind == "dict":
                dict_fields.append(f.name)
        return sorted(list_fields), sorted(dict_fields)

    def _render_container_decoders(
        self, list_fields: list[str], dict_fields: list[str]
    ) -> list[str]:
        """Render ``field_validator``s that parse env strings for containers.

        ``pydantic-settings`` json-decodes any complex-typed field's env
        value by default, which already handles genuine JSON (``[true,
        false]``, ``{"a": null}``); real env vars also feed list/dict
        settings as comma-separated or Python-literal strings (this is
        exactly what the mitol ``EnvParser`` list/crontab helpers produce),
        which raise ``SettingsError`` before the model ever instantiates.
        Paired with the ``NoDecode`` annotation on each field (see
        ``_render_field``), these validators receive the raw string and try
        ``json.loads`` first (so JSON inputs keep working exactly as
        before), then ``ast.literal_eval`` (Python-literal strings, e.g.
        single-quoted), then — lists only — a final comma-split fallback.
        """
        lines: list[str] = []
        if list_fields:
            choices = ", ".join(repr(name) for name in list_fields)
            lines.append(f'    @field_validator({choices}, mode="before")')
            lines.append("    @classmethod")
            lines.append(
                "    def _aqueduct_decode_list_fields(cls, value: object) -> object:"
            )
            lines.append(
                '        """Parse a list from a JSON, Python-literal, or '
                'comma-separated env string."""'
            )
            lines.append("        if not isinstance(value, str):")
            lines.append("            return value")
            lines.append("        try:")
            lines.append("            parsed = json.loads(value)")
            lines.append("        except (ValueError, TypeError):")
            lines.append("            try:")
            lines.append("                parsed = ast.literal_eval(value)")
            lines.append("            except (ValueError, SyntaxError):")
            lines.append("                parsed = None")
            lines.append("        if isinstance(parsed, list):")
            lines.append("            return parsed")
            lines.append('        return [item.strip() for item in value.split(",")]')
            if dict_fields:
                lines.append("")
        if dict_fields:
            choices = ", ".join(repr(name) for name in dict_fields)
            lines.append(f'    @field_validator({choices}, mode="before")')
            lines.append("    @classmethod")
            lines.append(
                "    def _aqueduct_decode_dict_fields(cls, value: object) -> object:"
            )
            lines.append(
                '        """Parse a dict from a JSON or Python-literal env string."""'
            )
            lines.append("        if not isinstance(value, str):")
            lines.append("            return value")
            lines.append("        try:")
            lines.append("            parsed = json.loads(value)")
            lines.append("        except (ValueError, TypeError):")
            lines.append("            parsed = None")
            lines.append("        if isinstance(parsed, dict):")
            lines.append("            return parsed")
            lines.append("        return ast.literal_eval(value)")
        return lines

    def _enrich_dicts(self) -> tuple[dict[str, str], list[TypedDictDef]]:
        """Return ``(enriched_annotations, typeddict_defs)`` for dict-valued fields.

        Uses genson (via ``dict_schema.enrich_dict_annotation``) to turn a
        ``dict[str, Any]`` literal into a precise ``dict[str, XxxEntry]`` plus
        the ``TypedDict`` definitions. Silently no-ops when genson is not
        installed (the ``[codegen]`` extra) or a value is not enrichable.

        Externally supplied ``dict_enrichment`` (see ``__init__``) is applied
        first and takes precedence per field name — it was already computed
        upstream (genson need not be importable *here* for it to apply).
        """
        enriched: dict[str, str] = {}
        defs: list[TypedDictDef] = []
        seen: set[str] = set()

        for name, (annotation, new_defs) in self._dict_enrichment.items():
            if annotation == "dict[str, Any]":
                continue
            if any(d.class_name in seen for d in new_defs):
                continue
            enriched[name] = annotation
            for d in new_defs:
                seen.add(d.class_name)
            defs.extend(new_defs)

        try:
            from django_aqueduct.codegen.dict_schema import (  # noqa: PLC0415
                enrich_dict_annotation,
            )
        except ImportError:
            return enriched, defs

        literal_kinds = (DefaultStrategy.LITERAL, DefaultStrategy.FACTORY)
        for f in self._fields:
            if f.name in enriched:
                continue
            if f.default.strategy not in literal_kinds:
                continue
            if not isinstance(f.default.literal, dict) or not f.default.literal:
                continue
            annotation, new_defs = enrich_dict_annotation(f.name, f.default.literal)
            if annotation == "dict[str, Any]":
                continue
            # Skip if a TypedDict name would collide with an already-emitted one.
            if any(d.class_name in seen for d in new_defs):
                continue
            enriched[f.name] = annotation
            for d in new_defs:
                seen.add(d.class_name)
            defs.extend(new_defs)
        return enriched, defs

    def _all_imports(self, *, has_containers: bool = False) -> frozenset[ImportSpec]:
        specs: set[ImportSpec] = set(_BASE_IMPORTS)
        if any(f.env_aliases for f in self._fields):
            specs.add(ImportSpec("pydantic", "AliasChoices"))
        if has_containers:
            specs.add(ImportSpec("ast"))
            specs.add(ImportSpec("json"))
            specs.add(ImportSpec("typing", "Annotated"))
            specs.add(ImportSpec("pydantic", "field_validator"))
            specs.add(ImportSpec("pydantic_settings", "NoDecode"))
        for f in self._fields:
            specs |= f.all_imports()
        return frozenset(specs)

    def render(self) -> str:
        """Return the complete generated module as a string."""
        enriched, typeddict_defs = self._enrich_dicts()
        list_fields, dict_fields = self._container_fields(enriched)
        specs = set(self._all_imports(has_containers=bool(list_fields or dict_fields)))
        if typeddict_defs:
            specs.add(ImportSpec("typing", "TypedDict"))
        imports = _render_imports(frozenset(specs))

        lines: list[str] = []
        lines.append(_COMMENT_BLOCK)
        lines.append("")
        lines.append(region_open("generated", "imports").lstrip())
        lines.append(imports)
        lines.append(region_close("generated", "imports").lstrip())
        lines.append("")
        lines.append("")
        if typeddict_defs:
            lines.append(region_open("generated", "typeddicts").lstrip())
            for td in typeddict_defs:
                lines.append(_render_typeddict(td))
            lines.append(region_close("generated", "typeddicts").lstrip())
            lines.append("")
            lines.append("")
        docstring = (
            '    """Typed Django settings model generated by django-aqueduct."""'
        )
        config_line = (
            f"    model_config = SettingsConfigDict("
            f'env_prefix="", extra="{self._extra}")'
        )
        lines.append(f"class {self._class_name}(BaseSettings):")
        lines.append(docstring)
        lines.append("")
        lines.append(config_line)
        lines.append("")
        no_decode_names = set(list_fields) | set(dict_fields)
        lines.append(region_open("generated", "fields"))
        lines.extend(self._render_grouped_fields(enriched, no_decode_names))
        lines.append(region_close("generated", "fields"))
        lines.append("")
        if list_fields or dict_fields:
            lines.append(region_open("generated", "container_decoders"))
            lines.extend(self._render_container_decoders(list_fields, dict_fields))
            lines.append(region_close("generated", "container_decoders"))
            lines.append("")
        lines.append(region_open("preserved", "validators"))
        lines.append("    # Add @model_validator / @field_validator methods here.")
        lines.append("    # This region is preserved across regeneration.")
        lines.append(region_close("preserved", "validators"))
        lines.append("")
        return "\n".join(lines)
